/**
 * Nomination categories for AECC Election.
 * Used in admin navigation and candidate filtering.
 */
export const NOMINATION_CATEGORIES = [
  { id: 'board_of_director', label: 'Board of Director', topCount: 7 },
  { id: 'secretary', label: 'Secretary', topCount: 1 },
  { id: 'treasurer', label: 'Treasurer', topCount: 1 },
  { id: 'audit_committee', label: 'Audit Committee', topCount: 3 },
  { id: 'election_committee', label: 'Election Committee', topCount: 3 },
] as const

export type NominationCategoryId = (typeof NOMINATION_CATEGORIES)[number]['id']

export function getTopCount(categoryId: string): number {
  return NOMINATION_CATEGORIES.find((c) => c.id === categoryId)?.topCount ?? 1
}

export const VALID_CATEGORY_IDS = NOMINATION_CATEGORIES.map((c) => c.id)

export function isValidCategory(id: string): id is NominationCategoryId {
  return VALID_CATEGORY_IDS.includes(id as NominationCategoryId)
}

export const MEMBERS = [
  'Abao, Ram Dave',
  'Abasula, Maria Rosario Soriano',
  'Abejar, Nerio Bago',
  'Abundo, Bonifacio Cuarental',
  'Aguadera, Nikke Evan Balais',
  'Agustin, Marvin Garces',
  'Agustin, Rolly Asaytona',
  'Alegado, Roceller Escobal',
  'Alloso, Janena Marie Cuerbo',
  'Almerol, Jhonelle Ayensa',
  'Almonte, Joel Jabao',
  'Alvarez, Nicanor Bacus',
  'Amper, Edgar Nemil',
  'Anino, Mesael Caholes',
  'Arcamo, Fe Yuson',
  'Avenido, Jestoni',
  'Balagot, Edilberto L.',
  'Ballara, Jekiri Buendia',
  'Banate, Tomas Arboleda',
  'Barbac, Roshell Curay',
  'Barrios, Jonel Neri',
  'Bero, Rommel Galope',
  'Boda, Sandy Casenas',
  'Bompat, Melquisedec Manabat',
  'Buba, Rammel Calo',
  'Bucol, Irven Tabada',
  'Butcon, Czarel Joe Cañosa',
  'Cabe, Jeanette Rosales',
  'Cabrera, Clark Anduyan',
  'Cadungog, Jovanie Perales',
  'Calo, Maria Carla Carmen Patrimonio',
  'Casinas, Ric Gesite',
  'Cebrian, Nelson Bisnar',
  'Cutamora, Don Karl',
  'Dabasol, Emie Ato',
  'Dagani, Felixberto III Paradero',
  'Daniel, Randy Ampong',
  'Dar, Ricky Castillo',
  'Dausin, Junjelyn',
  'Dawa, Rolando Yamomo',
  'Daymiel, Darwin Toledo',
  'De Chavez, Ariel Luna',
  'De La Cena, Daniel Jr. Martinez',
  'De Vera, Sergio Gabales',
  'Deferia, Jr., Romulo Dumdumaya',
  'Dela Peña, Gringo Lamanilao',
  'Delegencia, Lynneth Amparo',
  'Deroca, Dan Michael Bernardino',
  'Dolera, Johnny Entoy',
  'Dubouzet, Wynida Bejo',
  'Dueñas, Elisa Manaug',
  'Duterte, Eveen Grace Moreno',
  'Dy, Junie Martinez',
  'Erong, Rolly',
  'Escobar, Jeffrey Lumictin',
  'Esquida, Presilita Manuel',
  'Evanoso, Teddy Sastre',
  'Fabriga II, Ricardo Rafosala',
  'Flores, Karren Juntilla',
  'Fortun, Israel Planas',
  'Fumar, Gregorio Amper',
  'Galabay, Nowel Dominguez',
  'Gancino, Marisa Osorio',
  'Gantuangco, Rey Jay Erong',
  'Garay, Jason Yuting',
  'Gardose, Randy Olivar',
  'Guardiana, Jison Castorico',
  'Gumanit, Benjie Boy Savellon',
  'Gutierrez, Angela Mae Celmar',
  'Iting, Rodelo Daclan',
  'Jala, Ronnie Padon',
  'Jumalon, Jun Paul Balacuit',
  'Langheras, Joel Cutto',
  'Lim, Rhodora Olaer',
  'Lood, Rogelio Elondo',
  'Lugo, Rey Jayson Alcantara',
  'Lumalis, Vincent Escobido',
  'Martinez, Jr., Alberto Capablanca',
  'Martirizar, Kristoffer Gestano',
  'Maximo, Jr., Ruben Sotto',
  'May-as, Louvenjun Cabusas',
  'Mejala, Carlito',
  'Mongado, Jed Alutaya',
  'Montesco, Ronald',
  'Moron, Jonh Real Rabina',
  'Naife, Paul Joseph Bade',
  'Nayve, Maria Irene Yee',
  'Oraiz, Reygen Canoy',
  'Orquiz, Marcelino Nogas',
  'Osin, Jose Jr. Quizeo',
  'Otaza, Ria Asuncion Asis',
  'Padoga, Joy',
  'Pagara, Lorence Bacsarsa',
  'Pagente, Stanley Durango',
  'Paje, Jeremy Salas',
  'Pal, Alfredo Baguedan',
  'Pal, Ariel Paden',
  'Palado, Lourdes Pasok',
  'Pantoñal, Mary Grace Bardos',
  'Paradalla, Enriquito Talisic',
  'Pasco, Jay Calungsod',
  'Peregrino, Lindy',
  'Peligro, Mary Grace Togonon',
  'Plaza, Rolyn Bartolome',
  'Punay, Rogelio Pampilon',
  'Puzon, Aileen Faye',
  'Quiaman, Renie Veloz',
  'Raden, Michelle Geleen Rose Burdis',
  'Regalado, Roque Anotado',
  'Reyes, Leonel Jr. Duqueza',
  'Sabaricos, Jeziel Ermila',
  'Sablas, Anthony Aguillon',
  'Sagun, Leonel Tura',
  'Salupan, Elmer Hallera',
  'Salve, Maria Theresa Roperos',
  'Sasuman, Queen Susan Mordeno',
  'Sasuman, Reymond Yara',
  'Tabacon, Nestor Parpan',
  'Taculayan, Jimy Pasoc',
  'Tagoloan, Rhenie Pelubeda',
  'Talamo, Jimmy Pingoy',
  'Toledo, Jessie',
  'Tuyor, Ailysa Musico',
  'Villanueva, Victor Samonte',
  'Villamor, Reynaldo',
  'Yamit, Ariel Monte',
  'Yncierto, EmelPatric Mades',
  'Zamora, Willy Jay Cerna',
] as const
